### ISSUE TITLE
gzip files

### ISSUE THREAD

**Issue by kimoi** [ceesvanegmond/minify#58]
Would be good to gzip files on-disk instead of making the webserver do it every time it serves a file.

**Comment by sirsquall** [comment]
The file are stored on disk

**Comment by kimoi** [comment]
What? They are stored on disk, I'm suggesting to provide an option gzip after minification.

**Comment by sirsquall** [comment]
Ok sorry I miss understood. It's better to let apache handle the gzip compression.
