### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by nam-co** [ceesvanegmond/minify#59]
Hi, Thanks for the package is great, Elixir is just big, I was wondering, can I install it in L5? Im getting a error adMethodCallException in ServiceProvider.php line 226:
Call to undefined method [package]?

Should I use version 2.0.* or 3.0.*?

Thanks you for you time

**Comment by nam-co** [comment]
Sorry I just saw the new package, Question: how do I force the minify?

**Comment by sirsquall** [comment]
Hi,

When you push the configuration:
`php artisan config:publish ceesvanegmond/minify`

In the files:
`app/config/packages/ceesvanegmond/minify/config.php`

You have the `ignore_environments` you have juste to remove everything and the package will minify.
