### ISSUE TITLE
customize final URL

### ISSUE THREAD

**Issue by vics80** [ceesvanegmond/minify#61]
¡Great! ¡Works fine!

But I have several questions:

¿How can I customize final URL? I woud like to add this string "?v=32654" to the final of the URL.

The builds are created in every runtime? Can I created statically in production?

**Comment by sirsquall** [comment]
Hi,

No you cannot customize the url, and no the file are not created at each runtime.

We are using a md5 of the files array, and after we use `filetime` to read the last updated time for all the file. If you update any file, they are generated again.

Like that you didn't need to add a GET paremeter to the URL.
