### ISSUE TITLE
Path is not currect in the website 

### ISSUE THREAD

**Issue by sibinx7** [ceesvanegmond/minify#62]
Sir

Thanks for this good package for laravel. I have some issue with this package. I put public folder and put on the root, so in normal case i use 

{{HTML::style('public/css/style.css)}} it work well , but when i use this package i gave 

{{Minify::stylesheet('/css/v-front-common.css')}}

Output website become 

<link href="css/builds/850a53aa7231cd72d94674fb352063081423895179.css" rel="stylesheet">

So style is not loading on the website, actual root 

http:://localhost/videoreels/public/css/builds/<--stylesheet name-->

So is there any way to fix this one

When i gibe minift::stylesheet('/public/css/main.css') and ('public/css/main.css') it show error that

E:\MyWork\PHPWork\XAMP\htdocs\videoreels\publicpublic/css/v-front-common.css' does not exist

**Comment by sibinx7** [comment]
I just fix issue by editing Stylesheet.php in the minify directory

$attributes = array('href' => asset('public'.$file), 'rel' => 'stylesheet') + $attributes; now it work.

But i think we have {{HTML::style(<path>)}}, if minify also use same technique there is no need of any other modifications. May be it is difficult ( need to create a file and and move to builds folder, using paths instead of urls required for this operations)

**Comment by sirsquall** [comment]
Ok strage I'm using the `public_path` method the standart Laravel

And to add the file It's look like that : 
`
    /**
     * @param  $file
     * @return void
     * @throws \CeesVanEgmond\Minify\Exceptions\FileNotExistException
     */
    public function add($file)
    {
        if (is_array($file))
        {
            array_map(array($this, 'add'), $file);
        }
        else
        {
            $file = $this->publicPath . $file;
            if (!file_exists($file))
            {
                throw new FileNotExistException("File '{$file}' does not exist");
            }

            $this->files[] = $file;
        }
    }
`

If the file is not found an exception should be raise, but it's strange.
