### ISSUE TITLE
base_url Not working ?

### ISSUE THREAD

**Issue by xagaroo** [ceesvanegmond/minify#63]
I'm using minify with laravel in 2 servers, my own local machine where it works ok with a virtual host, and a server with an URL like:

http://111.222.333.444/somefolder/

On this server, minify builds something like

<link href="/assets/css/builds/3dc89d2dd0793c4430d0412b845a39b11426175520.css" rel="stylesheet">

that is not correct because the route is /somefolder/assets....

even when I put 'base_url' configuration.

Something is wrong or am I doing something wrong?

**Comment by sirsquall** [comment]
To use the base_url, you should remove the "->withFullUrl()"
