### ISSUE TITLE
Relative img path

### ISSUE THREAD

**Issue by FDiskas** [ceesvanegmond/minify#64]
in css
```
background: url(../img/pattern/boxed-pattern1.gif);
```
will generate:
```
background: url(../img/pattern/boxed-pattern1.gif);
```
will compress and saves compressed css inside folder, but path to the images was not corrected.
Here is the config:
```
'css_build_path' => '/css/builds/',
```

I think that generated css paths to the static images must be generated as:
```
background: url(../../img/pattern/boxed-pattern1.gif);
```

**Comment by sirsquall** [comment]
The generator don't update the path, I recommand you to put, the builds directory a the same level as css.

Like that
./css
./img
./builds

**Comment by FDiskas** [comment]
This functionality must be.

Vytenis Kučiauskas
