### ISSUE TITLE
Bootstrap glyph icons not working after compression

### ISSUE THREAD

**Issue by asdf072** [ceesvanegmond/minify#65]
Whenever I enable the plugin, the glyph icons in Bootstrap display incorrectly as empty boxes. Like the character encoding is changed. Is there a fix?

I just found that the icon fonts are created with the content css attribute, like:

content: "\e001";

**Comment by sirsquall** [comment]
Hello,

This package it's only a wrapper for laravel, the minify is rendered by this package:
https://github.com/natxet/CssMin

You shoud post you issue in their repository.

**Comment by Varun-Varunesh** [comment]
I am also having this same issue. Bootstrap glyph icons are coming incorrectly as empty boxes. I am using laravel 4.2 and minifying the assets using ceesvanegmond-minify.

**Comment by sirsquall** [comment]
Please read my comment, you should create your issue in the pacakge : https://github.com/natxet/CssMin

Thanks
