### ISSUE TITLE
How to deal with relative urls for resources? 

### ISSUE THREAD

**Issue by TimTruston** [ceesvanegmond/minify#67]
Once you minify css and js all the relative urls go to on one file. And many resources e.g. images get linked wrong from your css or js.  How do you deal with relative urls for resources? Or u have to edit all urls used in css and js files to be absolute? I have had to manually do that.

**Comment by sirsquall** [comment]
Well you should place the build folder in the same folder as your cs/js folders... you get something like this:

assets/
|-css/
|-js/
|-img/
|-fonts/
|-build/
Then you reference in your css, the fonts and images as being ../fonts/font.eof and ../img/image.png and the folder structure holds.
