### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by rotaercz** [ceesvanegmond/minify#68]
After following your instructions and then doing:

```
php artisan config:publish ceesvanegmond/minify
```

I'm getting the error:

```
PHP Fatal error:  Class 'CeesVanEgmond\Minify\MinifyServiceProvider' not found in /var/www/laravel/bootstrap/compiled.php on line 4485
```

{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'CeesVanEgmond\Minify\MinifyServiceProvider' not found","file":"\/var\/www\/laravel\/bootstrap\/compiled.php","line":4485}}

What do I have to do to solve this issue?

**Comment by rotaercz** [comment]
I had to do:

```
composer update
```

before publishing the config file. Maybe add it to your instructions?

**Comment by sirsquall** [comment]
Yes ofc, otherwise the package are not downloaded.
